/Users/federicomoreno/PycharmProjects/UCEMA/02-data-sources/02-numpy/01-intro


In [9]:
print("hello")

hello


In [10]:
#Import the necessary libraries
from PIL import Image
from numpy import asarray


img = Image.open('img.png')

# asarray() class is used to convert
# PIL images into NumPy arrays
numpydata = asarray(img)

# <class 'numpy.ndarray'>
print(type(numpydata))


<class 'numpy.ndarray'>


In [11]:

#  shape
print(numpydata.shape)



(1280, 1920, 4)


In [3]:

# data
print(numpydata)

[[[ 20 126 201 255]
  [ 20 126 201 255]
  [ 20 126 201 255]
  ...
  [  0 116 188 255]
  [  0 120 192 255]
  [  0 125 196 255]]

 [[ 20 126 201 255]
  [ 20 126 201 255]
  [ 20 126 201 255]
  ...
  [  0 120 192 255]
  [  0 123 195 255]
  [  0 126 197 255]]

 [[ 20 126 201 255]
  [ 20 126 201 255]
  [ 20 126 201 255]
  ...
  [  0 126 197 255]
  [  0 126 197 255]
  [  0 126 197 255]]

 ...

 [[  0  23  59 255]
  [  0  23  59 255]
  [  0  25  60 255]
  ...
  [ 70  81  54 255]
  [135 146 120 255]
  [149 160 134 255]]

 [[  0  22  57 255]
  [  0  23  58 255]
  [  0  25  60 255]
  ...
  [  0   5   0 255]
  [ 20  31   4 255]
  [ 98 109  82 255]]

 [[  0  21  56 255]
  [  0  23  58 255]
  [  0  25  60 255]
  ...
  [ 13  24   0 255]
  [ 10  22   0 255]
  [ 15  25   0 255]]]
